name: Docker Image CI

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build the docker image
    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the Docker image
      # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: cd client && docker build -t ${{ secrets.DOCKER_USERNAME }}/cb-baseline:4.0.2 -f ../docker/Dockerfile .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cb-baseline:4.0.2

      
      - name: Build the server Docker image
        run: cd ../server && docker build -t ${{ secrets.DOCKER_USERNAME }}/cb-baseline-server:4.0.2 -f ../docker/server/Dockerfile .
        
      - name: Push the serve Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cb-baseline-server:4.0.2
 
